name: Simple CI Example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Загрузка кода
        uses: actions/checkout@v3

      - name: Проверка HTML-файла
        run: |
          test -f index.html && echo "Файл найден!"
